### PR TITLE
Adds per-container-ip detection.

### PR DESCRIPTION
**Pull request by cheuschober**
Hi. This pull request adds per-container IP detection similar to the way provided by mesos-dns which is a necessary feature for such networking models as Calico.

Port number discovery is currently not functioning since no labels have yet been designated for service ports as have been for Container IP's.

Also applied `go fmt`.

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
What version of Mesos are you running that has the ip labels in the task status? mesos-consul is currently targets 0.22.1

I have a 0.3 branch that I would like to add this to instead of merging into master.

**Comment by cheuschober** [comment]
We're running a custom 0.24-ish mesos and a custom 0.11-ish marathon. This is all in service of shoehorning calico-docker into mesos to enable per-container-ip's. Feel free to suggest pointing this at whatever branch you feel is most appropriate. I have a few other ideas down the road for `mesos-consul` enhancements (and a pretty dedicated professional investment) but thought it'd be worthwhile to just open the dialogue sooner rather than later.

**Comment by stevendborrelli** [comment]
@cheuschober by any chance are you at MesosCon?  I'd love to talk.

**Comment by cheuschober** [comment]
Absolutely! If you're here as well I'd love to meet.

**Comment by cheuschober** [comment]
Closing and retargeting for 0.3

**Pull request closed without merging**
