### PR TITLE
CiscoCloud -> mantl in Docker build

### PR DESCRIPTION
**Pull request by ChrisAubuchon**

### CODE REVIEW

**Comment by ChrisAubuchon** [comment]
Addresses https://github.com/mantl/mesos-consul/issues/111

**Review by somethingwithproof — APPROVED** [review]
LGTM

**Comment by wichitalineman** [comment]
Dockerfile in project is still referencing CiscoCloud which causes a build fail

`COPY . /go/src/github.com/CiscoCloud/mesos-consul`
`RUN apk add --update make git glide \`
`	&& cd /go/src/github.com/CiscoCloud/mesos-consul \`

Changing from CiscoCloud to mantl in the file fixes the build.

**Review by Cryptophobia — APPROVED** [review]
LGTM!

**Comment by Cryptophobia** [comment]
@Theaxiom : Per @wichitalineman , should we merge?

**Pull request merged**
