### PR TITLE
Configurable consul endpoint address

### PR DESCRIPTION
**Pull request by sashkachan**
Adds address option to consul.

### CODE REVIEW

**Comment by michaeljs1990** [comment]
Why is it not configurable to change the consul endpoint? Possibly i'm missing something in how this is suppose to work but it seems the way it runs right now every single docker contianer needs to run consul which seems needlessly excessive.

**Comment by mattkanwisher** [comment]
I was confused about this also? Is the assumption the Mesos server itself is running consul? Seems pretty safe to add this patch

**Comment by ChrisAubuchon** [comment]
Due to the design on Consul, every mesos agent needs to run consul. mesos-consul connects to a consul instance that is running on the same node as the service is running on. Specifying a central consul endpoint will result in services being registered on that endpoint instead of on the mesos agent as they should be.

**Comment by mattkanwisher** [comment]
So I installed consul agent on all my mesos nodes, however it appears this code tries to access consul agent on a public interface not on 127.0.0.1, so it won't find it. As we dont want that exposed on the network.

**Comment by evilezh** [comment]
+1

**Comment by ernestas-poskus** [comment]
:+1:

**Comment by thomas-maurice** [comment]
+1

**Review by kopinions — APPROVED** [review]

**Comment by sjkyspa** [comment]
when it will be merged?

**Comment by Theaxiom** [comment]
@sjkyspa When the build completes successfully. 👍

**Comment by Theaxiom** [comment]
It also needs to be rebased to master first.

**Comment by ChrisAubuchon** [comment]
If you specify a consul agent, then all of the registered services will be assigned to that agent. So if you have a process running on say, mesos-worker-1, and register the service on consul-master-1, if consul-master-1 becomes unavailable then the service running on mesos-worker-1 goes critical. Which is clearly incorrect. I have specifically not merged this for that reason.

**Pull request closed without merging**
