### PR TITLE
Remove default health-check ip

### PR DESCRIPTION
**Pull request by ernestas-poskus**
@ChrisAubuchon @atongen @erSitzt 

This makes health check server to listen on all network interfaces. I had problem since default ip is localhost or lo interface running mesos health checks is not possible since by default it listens on localhost and there is no change to now docker IP in advance to set it via flag.

Note: removal does not change previous behavior but rather improves it.

### CODE REVIEW

**Review by somethingwithproof — APPROVED** [review]
LGTM

**Review by Theaxiom — APPROVED** [review]
LGTM 👍

**Comment by Theaxiom** [comment]
Can we get current master ff'd into this branch before we merge?

**Comment by ernestas-poskus** [comment]
@Theaxiom rebased

**Comment by Theaxiom** [comment]
Thank you!

**Pull request merged**
